### ISSUE TITLE
Tunneling issue in RigidBody2d

### ISSUE THREAD

**Issue by souvikinator** [appsinacup/godot-rapier-2d#42] opened 2024-03-29 07:33 UTC
**Describe the bug**
On applying impulse or force on RigidBody2d by a CharacterBody2d the body moves out of the scene through walls. 
Without rapier extension it works fine.

**To Reproduce**

https://github.com/appsinacup/godot-rapier-2d/assets/64456160/8b42fd46-300f-4977-b6c9-cc599395e222

**Expected behavior**
Even after setting infinite impulse to false and making the collision walls (StaticBody2d with CollisionShape2d)  the RigidBody2d should not phase through the wall / scene.

**Screenshots**
(video attached)

**Environment (please complete the following information):**
 - OS: Windows 11
 - Version v0.5.1
 - Godot Version v4.2

**Comment by Ughuuu** [comment] 2024-03-29 08:51
Can you attack a project and a way of reproducing?

**Comment by Ughuuu** [comment] 2024-03-29 22:46
In any case, it looks like a kinematic body goes to push a rigidbody to a static body. I don't think there is much to be done here, sure the rb is pushed out of existence, maybe if you make the static wall bigger it might not, but there isn't much I can do as wrapper of rapier2d.

**Comment by Ughuuu** [comment] 2024-03-30 14:07
Closing as there isn't a project for repro. Reopen if you have that, but in any case, looks like there isn't much I can do from plugin side to fix this, and it seems like this is the right behaviour in this case.

**Closed by Ughuuu** 2024-03-30 14:07 UTC
Labels: bug

**Comment by souvikinator** [comment] 2024-03-30 17:43
> Can you attach a project and a way of reproducing?

Added the github link to repo.

**Comment by Ughuuu** [comment] 2024-03-30 19:37
Took a look, and they look very similar. I would say it's not really a bug, and you shoudln't do that ideally(moving the character controller that close to the rigidbody, and then the rigidbody doesn't have much of a choice, either goes through the wall or teleports, it's hard).
I would say in this case you could make the characterbody a rigidbody with a high mass, and play with numbers until it works.
